version: "3.8"
services:
  app:
    build: .
    container_name: stock_bot
    ports:
      - "5000:5000"  # Adjust if you're running a server
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
